### ISSUE TITLE
Get the theme listed on flathub

### ISSUE THREAD

**Issue by CharoSW** [lassekongo83/adw-gtk3#12] opened 2022-01-26 05:41 UTC
A current bit of pain is that the theme doesn't work with flatpak programs because of the system sandboxing.  it would be handy to have it listed so that it applies better on systems that make a lot of use of flatpaks

**Comment by SilverMarcs** [comment] 2022-01-26 08:07
Meanwhile use [stylpak](https://github.com/refi64/stylepak)

**Comment by dusansimic** [comment] 2022-01-30 19:42
I could work on this, I've already made a few theme packages for personal use and maintain some flatpak packages on flathub. Ideally, theme should be versioned so new releases could be uploaded on flathub once they land.

**Comment by lassekongo83** [comment] 2022-01-30 19:50
@dusansimic Great! There are however a few things I need to fix before I'll start versioning the theme.

**Comment by lassekongo83** [comment] 2022-02-04 12:58
@dusansimic The theme now has a first version release: https://github.com/lassekongo83/adw-gtk3/releases

**Comment by dusansimic** [comment] 2022-02-04 14:58
@lassekongo83 Fantastic 🚀. I've made the first version of the flatpak manifest for the theme and it works however there are two issues, one small and one large.

1. The flatpak package will need to be named `org.gtk.Gtk3theme.adw-gtk3` which stands out capitalization wise (all other themes use kebab-pascal case [link](https://github.com/orgs/flathub/repositories?q=org.gtk.Gtk3theme&type=source)). I'm guessing there won't be any particular problem for the package name to be regular kebab case but it might be worth considering changing the name. The problem is that flatpak checks the name of the theme in the system (that would be `adw-gtk3` or `adw-gtk3-dark`) and tries to find a package with the matching name but it's case sensitive. It could be left as is for now untils I send out a pr for adding it to flathub and then we'll see where we stand.
2. Dark and light theme can't be split up correctly since dark theme is just a symlink to the light theme directory. This creates a problem because flatpak differentiates dark and light theme by having separate packages for each one (see theme list in previous link). If both dark and light theme are in one package, when dark theme is selected (gtk-theme value in dconf i set to `adw-gtk3-dark`) it falls back to default Adwaita light since there is no `org.gtk.Gtk3theme.adw-gtk3-dark` pacakge. On the other hand when light theme is selected, it uses the dark adw-gtk3 theme for some reason. I think this should be handled in this repo so themes could be split in other packages too if that's needed. I might be able to help out with this however I haven't had much experience with meson before. I think it could be done with options ([arc-theme](https://github.com/jnsh/arc-theme) as an example) so for light/dark package it could be just specified which theme should be built.

I think that is everything for now.

**Comment by lassekongo83** [comment] 2022-02-04 16:49
I guess I need to study some more meson as well.

**Comment by lassekongo83** [comment] 2022-02-05 09:17
@dusansimic The dark theme is no longer a symbolic link in the v1.0.1 release.

As for the first issue. I'll wait and see, as renaming the project could cause issues for people when it's updated.

**Comment by dusansimic** [comment] 2022-02-05 12:24
Awesome! Theme now seems to work however it would be great if there could be a built package for the theme, at least for now until meson build definition is reworked to support options. I saw that there was one for v1.0 but there isn't one for v1.0.1. Sorry for the back and forth.

I'll probably send a pr for the package on Monday since I'm a bit busy this weekend.

**Comment by lassekongo83** [comment] 2022-02-05 12:33
Added a tar.xz package to the release.

**Comment by dusansimic** [comment] 2022-02-08 13:54
@lassekongo83 Theme submissions are merged and published on flathub 🥳.

**Closed** 2022-02-08 14:31 UTC
Labels: help wanted

**Comment by SaadiSave** [comment] 2022-03-04 10:42
@dusansimic Why isn't the flatpak theme working?
