### ISSUE TITLE
Shadow area is clickable area for server-side decorations under XWayland

### ISSUE THREAD

**Issue by im-tem** [lassekongo83/adw-gtk3#251] opened 2024-01-16 09:51 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [ ] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

Clicking on the shadow area of an XWayland window using server-side decorations with adw-gtk3 theme applied registers as a click on the window and therefore prevents switching focus to the application behind the shadow. Visual example: clicking on the GNOME tweaks window here does nothing
![image](https://github.com/lassekongo83/adw-gtk3/assets/18075164/e5af1457-2109-4bd1-b3b2-f95b15ebc04c)

This issue cannot be replicated using the Adwaita theme.

### OS and version [e.g Fedora 37]

Fedora 39

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

5.2 tar.xz + 5.1 flatpak

### GNOME version

45.2

**Comment by lassekongo83** [comment] 2024-01-16 10:06
Duplicate of #228
Nothing can be done in the theme except completely removing the shadow. Apparently this bug should've been fixed: https://gitlab.gnome.org/GNOME/mutter/-/issues/2788 But maybe there was a regression?

**Closed by lassekongo83** 2024-01-16 10:06 UTC
