### ISSUE TITLE
Squared-off corners in wifi menu.

### ISSUE THREAD

**Issue by DuttaAB-dev** [lassekongo83/adw-gtk3#36] opened 2022-02-18 18:15 UTC
![image](https://user-images.githubusercontent.com/61903332/154739268-d4f04957-4545-48f6-9255-b732a6bbc95c.png)
The heading is self-descriptive and this here is an example.

Simply put, the wifi list is having sharp corners.

**Comment by lassekongo83** [comment] 2022-02-18 19:17
I found that non `.content` lists are a bit trickier to style. I have a style that sort of works, but it may have some bugs that can't be fixed. (`:last-child` border roundness not working, shadow artifacts, and applications that may break if the style is used.)

Try adding this to your `~/.config/gtk-3.0/gtk.css` and see if you notice any breakage or bugs in any apps.

```css
list.view.frame { padding: 0; background-color: #ffffff; color: rgba(0, 0, 0, 0.8); border-radius: 12px; box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.03), 0 1px 3px 1px rgba(0, 0, 0, 0.07), 0 2px 6px 2px rgba(0, 0, 0, 0.03); }
list.view.frame:backdrop { background-color: #ffffff; }
list.view.frame separator { margin: 0; background-color: #e1e1e1; }
list.view.frame > row { margin: 0; padding: 2px; transition: 200ms cubic-bezier(0.25, 0.46, 0.45, 0.94); border-radius: 12px; }
list.view.frame > row:not(:last-child) { border-bottom-left-radius: 0; border-bottom-right-radius: 0; }
list.view.frame > row:not(:first-child):not(:last-child) { border-radius: 0; -gtk-outline-radius: 0; }
list.view.frame > row:first-child { border-top-left-radius: 12px; border-top-right-radius: 12px; -gtk-outline-radius: 12px 12px 0 0; }
list.view.frame > row:last-child { border-top-left-radius: 0; border-top-right-radius: 0; border-bottom-left-radius: 12px; border-bottom-right-radius: 12px; -gtk-outline-radius: 0 0 12px 12px; }
list.view.frame > row:only-child { border-bottom: none; border-radius: 12px; -gtk-outline-radius: 12px; }
list.view.frame > row:not(:selected):hover { background-color: #f9f9f9; border-radius: 12px; }
```

**Comment by DuttaAB-dev** [comment] 2022-02-19 18:49
Okay... On it. Will update you on my findings.

**Comment by DuttaAB-dev** [comment] 2022-02-22 11:27
So been testing the changes that you suggested and there's nothing noticeable as of yet. Even the wifi menu is still the same. 
Neither are there any bugs or weird glitches. Also I discovered that the same issue is present in some other menus in the gnome settings app that in my guess, uses the same widget. For example :-
![image](https://user-images.githubusercontent.com/61903332/155123144-3f22422c-05c0-412c-9aca-76bb033edb42.png)

![image](https://user-images.githubusercontent.com/61903332/155123186-983e6c74-ae39-404a-b771-5ce18d77436f.png)

![image](https://user-images.githubusercontent.com/61903332/155123232-7e01d087-1d55-4e01-8939-d889a2fe4dfe.png)
And some more...

**Comment by lassekongo83** [comment] 2022-02-22 13:25
Here are some bugs I've found:
![bugs](https://user-images.githubusercontent.com/7415624/155140855-419683e4-0047-4869-8d3b-0481435a5ffa.png)
1. Shadow leftovers on the left when switching pages.
2. No shadow on the right.
3. `:last-child` not working on the last row.

I also inspected the list in the online accounts section, and those are too generic to apply any style to. It doesn't have any unique css classes, so trying to force the same style on that one will most likely cause breakage.

I think I'm just going to leave it as is for now.

**Comment by DuttaAB-dev** [comment] 2022-02-22 14:33
On further testing, I noticed a few more bugs.

![image](https://user-images.githubusercontent.com/61903332/155152385-6b8e0e43-cba1-4dfe-b6c3-13a7dcf116bd.png)
The "Applications" section does not follow the dark style theme properly.

![image](https://user-images.githubusercontent.com/61903332/155152624-9a031774-3b36-4155-a5eb-9fe67d7eb03e.png)
Same with other sub-menus.

![image](https://user-images.githubusercontent.com/61903332/155153139-e696955d-477d-4dd5-86a9-3d24295126f0.png)
Some previously angled corners are not rendered properly(here, Gnome web)

**Comment by DuttaAB-dev** [comment] 2022-02-22 14:39
>I think I'm just going to leave it as is for now.

@lassekongo83 agreed, as this just broke more stuff instead of fixing anything. Maybe these widgets being "legacy" gtk3, they did not bother to attach proper css classes to them and hardcoded the styling?

**Comment by lassekongo83** [comment] 2022-02-22 15:46
> On further testing, I noticed a few more bugs.

Remove the style from `~/.config/gtk-3.0/gtk.css` if you haven't already.

> Maybe these widgets being "legacy" gtk3, they did not bother to attach proper css classes to them and hardcoded the styling?

Possibly. It was things that libhandy could solve, but since everyone is moving to libadwaita now I don't think we'll see any more legacy updates on these widgets.

**Comment by lassekongo83** [comment] 2022-02-22 18:37
Can't reproduce anything in https://github.com/lassekongo83/adw-gtk3/issues/36#issuecomment-1047857258

**Closed** 2022-07-29 13:31 UTC
