### ISSUE TITLE
Hardcoded Colour Issue

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [lassekongo83/adw-gtk3#279] opened 2024-11-30 23:56 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [ ] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [ ] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [ ] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

The hardcoded colour within this theme prevents other projects like the gnome Firefox theme from being able to detect gnome's picked accent colour

### OS and version [e.g Fedora 37]

Fedora 41

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

n/a (most recent Flathub version)

### GNOME version

47

### Application name and version (If the issue is with an app.)

Firefox 134

**Comment by lassekongo83** [comment] 2024-12-01 03:28
Duplicate of #277

**Closed by lassekongo83** 2024-12-01 03:28 UTC
Labels: duplicate
