### ISSUE TITLE
Flatpaks not following the theme

### ISSUE THREAD

**Issue by SkelyTony** [lassekongo83/adw-gtk3#134] opened 2022-05-30 10:11 UTC
### Describe the issue
Some Flatpak apps don't follow the theme. When the theme is set to normal adwaita via gnome-tweaks, they follow it correctly. The apps don't use the correct light/dark theme and even have non rounded corners when not maximized.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/78977752/170970242-6a6c2930-50f7-4ce7-9a36-b31f9b274714.png)

### Versions

- OS and version:  Fedora 36 silverblue
- GNOME Version: 42

### Settings

- [x] I installed the theme from the tarball.
- [ ] I installed the theme from git.
- [ ] I installed the theme from AUR.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [x] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [x] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment] 2022-05-30 10:15
Duplicate of https://github.com/lassekongo83/adw-gtk3/issues/101

**Closed by lassekongo83** 2022-05-30 10:15 UTC
Labels: duplicate
