### ISSUE TITLE
Adw-gtk3 and accent colours

### ISSUE THREAD

**Issue by LalOpen** [lassekongo83/adw-gtk3#278] opened 2024-11-28 17:36 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [X] I have created a new user profile without any modifications except adw-gtk3.

### Description

Hi!
Since GNOME 47 was released, an accent colour can now be set to the Shell and GTK4 apps.

For now, adw-gtk3 does not provide any other colour than the default blue.
As adw-gtk3 is a great solution for the ones who like to have consistency on their DE, I think it would be nice if adw-gtk3 could also provide accent colour support for GTK3 apps.

Is this technically feasible?
And if yes, do you consider to add support for the other colours that were implemented into GNOME ?

Thanks a lot!

### OS and version [e.g Fedora 37]

Fedora 41

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

5.5 git main branch

### GNOME version

47

**Comment by lassekongo83** [comment] 2024-11-28 19:48
Duplicate of #269

Also, it seems the only way for this to be possible in a more user friendly manner is by creating a 3rd party application/gnome extension that sets the accent colors (not gnome settings). It could simply change the gsettings value `gsettings set org.gnome.desktop.interface accent-color 'green'` and add an accent-color to the gtk config files `~/.config/gtk-4.0/gtk.css` etc.

**Closed by lassekongo83** 2024-11-28 19:48 UTC

**Comment by mrme8895** [comment] 2024-12-08 05:50
Does `~/.config/gtk-3.0/gtk.css` affect flatpak applications?

**Comment by lassekongo83** [comment] 2024-12-08 06:45
@mrme8895 No. You'll need to add an override: `sudo flatpak override --filesystem=xdg-config/gtk-3.0`
