### ISSUE TITLE
Dark border around xwayland windows

### ISSUE THREAD

**Issue by drakkar1969** [lassekongo83/adw-gtk3#220] opened 2023-04-02 11:28 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [ ] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

This theme produces a weird dark border around some windows:

![image](https://user-images.githubusercontent.com/18715287/229349800-93e9e086-49f3-47cb-af47-e796629a7483.png)

I am running GNOME on Wayland, and this only affects xwayland windows. The app shown in the screenshot is Mailspring, but the same issue affects e.g. VSCodium when run on xwayland (i.e. without wayland start flags).

Other GTK3 themes (e.g. Arc) do not have the same issue. Not using Flatpak apps btw.

### OS and version [e.g Fedora 37]

Arch Linux

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

4.4.r5.9cf9cb3-1

### GNOME version

43.4

**Comment by lassekongo83** [comment] 2023-04-02 11:37
Duplicate of https://github.com/lassekongo83/adw-gtk3/issues/20

The dark border is there because of https://github.com/lassekongo83/adw-gtk3/issues/18

And in Gnome 44 the legacy decorations will switch to gtk4, so there is no point in trying to fix this.

**Closed by lassekongo83** 2023-04-02 11:37 UTC
Labels: duplicate

**Comment by drakkar1969** [comment] 2023-04-02 11:39
Thanks, hadn't found the related issues ...
