### ISSUE TITLE
GTK3 apps don't have libadwaita style context menus

### ISSUE THREAD

**Issue by AlphaCraft9658** [lassekongo83/adw-gtk3#164] opened 2022-08-10 09:46 UTC
### Description
When opening a context menu inside a gtk-3 app the menu uses the gtk-3 defalt style but not the libadwaita look and feel.

### Screenshots

![image](https://user-images.githubusercontent.com/77483478/183869739-239d4313-004b-4114-9320-3b14ac9e3857.png)
![image](https://user-images.githubusercontent.com/77483478/183870288-8657d6f6-f25f-438f-a25b-6e9c7073d961.png)

### Versions

- OS and version: Fedora 36
- GNOME Version: 42

### Settings

- [x] I installed the theme from the tar.xz file.
- [ ] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [ ] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [x] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [x] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment] 2022-08-10 10:06
Duplicate of https://github.com/lassekongo83/adw-gtk3/issues/100

**Closed by lassekongo83** 2022-08-10 10:06 UTC
Labels: duplicate
