### ISSUE TITLE
Adw-gtk3 does not respect accent color selected from Gnome 47's settings

### ISSUE THREAD

**Issue by saulfgonzalez** [lassekongo83/adw-gtk3#273] opened 2024-10-09 09:06 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

I am not sure if this is an intended feature bugging out or just something that cannot be changed, but since upgrading to Gnome 47 I've been utilizing the new accent colors feature and I have notice my GTK3 apps still default to the default blue accent color. 

I was wondering if there is a way to change just the accent color to follow GTK4's settings. (Either automatically or manually - I checked out the adw-colors project but there seems to be no mention there of the new accent colors in Gnome 47).

### OS and version [e.g Fedora 37]

Fedora 41 Beta

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

5.4,  tar.xz

### GNOME version

47

**Comment by lassekongo83** [comment] 2024-10-09 10:08
Duplicate of #269

**Closed by lassekongo83** 2024-10-09 10:08 UTC
